variables:
  DB_NAME: "overhaul_media_drivewyze"
  CLIENT_NAME: "overhaul_media"
  PROJECT_NAME: "drivewyze"
  GIT_STRATEGY: none
  DEPLOY_MODE: wp
stages:
- deploy

deploy_develop:
  stage: deploy
  script:
  - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=develop --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --deploy-mode=$DEPLOY_MODE --backup-database --keep-uploads --npm-run="build"
  only:
  - develop
  tags:
  - develop

deploy_master:
  stage: deploy
  script:
    - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=master --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --deploy-mode=$DEPLOY_MODE --backup-database --keep-uploads --npm-run="build"
  only:
  - master
  tags:
  - master
  
deploy_other:
  stage: deploy
  script:
  - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=$CI_COMMIT_REF_NAME --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --deploy-mode=$DEPLOY_MODE --import-database
  except:
  - develop
  - master
  tags:
  - other
